/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fmontiel.eventos.views.personasview;

import com.fmontiel.eventos.interfaces.CallbackInterface;
import com.fmontiel.eventos.models.PersonaModel;
import com.fmontiel.eventos.services.PersonasService;
import java.io.IOException;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author PC
 */
public class Formulario extends javax.swing.JFrame {

    private Long eventoId;
    private PersonaModel persona;
    private CallbackInterface onFinish;
    private Formulario.Modos modo;
    private PersonasService personasService;

    public static enum Modos {
        AGREGAR,
        EDITAR
    }

    public Formulario(
            Formulario.Modos modo,
            Long eventoId,
            PersonaModel persona,
            CallbackInterface onFinish) {

        this.modo = modo;
        this.eventoId = eventoId;
        this.persona = persona;
        this.onFinish = onFinish;
        this.personasService = new PersonasService();

        initComponents();

        if (modo == Formulario.Modos.EDITAR) {
            textFieldCUI.setText(persona.getId().toString());
            textFieldCUI.disable();
            textFieldNombre.setText(persona.getNombre());
            textFieldEmail.setText(persona.getEmail());
            textFieldTelefono.setText(persona.getTelefono());
            btnAccion.setText("Editar");
        }
    }

    private void agregarPersona() {
        try {
            PersonaModel nuevaPersona = new PersonaModel();
            nuevaPersona.setId(Long.valueOf(textFieldCUI.getText()));
            nuevaPersona.setNombre(textFieldNombre.getText());
            nuevaPersona.setEmail(textFieldEmail.getText());
            nuevaPersona.setTelefono(textFieldTelefono.getText());

            PersonaModel personaAgregada = personasService.addPersonaToEvento(eventoId, nuevaPersona.getId(), nuevaPersona.getNombre(), nuevaPersona.getEmail(), nuevaPersona.getTelefono());

            JOptionPane.showMessageDialog(this, "Persona agregada correctamente");
            onFinish.call(new JSONObject().put("status", "added").put("personaId", personaAgregada.getId()));
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al agregar persona: " + e.getMessage());
        }
    }

    private void editarPersona() {
        try {
            
            persona.setNombre(textFieldNombre.getText());
            persona.setEmail(textFieldEmail.getText());
            persona.setTelefono(textFieldTelefono.getText());

            PersonaModel personaActualizada = personasService.updatePersonaInEvento(eventoId, persona.getId(), persona);

            JOptionPane.showMessageDialog(this, "Persona actualizada correctamente");
            onFinish.call(new JSONObject().put("status", "updated").put("personaId", personaActualizada.getId()));
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar persona: " + e.getMessage());
        }
    }

    private void btnRealizaraccion(java.awt.event.ActionEvent evt) {                                         
        if (Formulario.Modos.AGREGAR == modo) {
            agregarPersona();
        } else if (Formulario.Modos.EDITAR == modo) {
            editarPersona();
        }
        dispose();
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        btnAccion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldCUI = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Persona");

        btnAccion.setText("Agregar");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizaraccion(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Email");

        jLabel4.setText("Teléfono");

        jLabel5.setText("Cui");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldNombre)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addComponent(textFieldEmail)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addComponent(textFieldTelefono)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addComponent(textFieldCUI)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnAccion)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    /**
     * @param args the command line arguments
     */
    /*
     * public static void main(String args[]) {
     * 
     * 
     * try {
     * for (javax.swing.UIManager.LookAndFeelInfo info :
     * javax.swing.UIManager.getInstalledLookAndFeels()) {
     * if ("Nimbus".equals(info.getName())) {
     * javax.swing.UIManager.setLookAndFeel(info.getClassName());
     * break;
     * }
     * }
     * } catch (ClassNotFoundException ex) {
     * java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * } catch (InstantiationException ex) {
     * java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * } catch (IllegalAccessException ex) {
     * java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     * java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.
     * logging.Level.SEVERE, null, ex);
     * }
     * //</editor-fold>
     * 
     * 
     * java.awt.EventQueue.invokeLater(new Runnable() {
     * public void run() {
     * new Formulario().setVisible(true);
     * }
     * });
     * }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textFieldCUI;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
